### ISSUE TITLE
Typos and mistakes

### ISSUE THREAD

**Issue by sindikat** [math-comp/mcb#25]
Page 41: line 6 of Exercise 1 has `= true : bool` as an output, should have `= false : bool` instead

Page 46: "swell-formed"?

Page 56: "back yo our example" should be "back to our example"

Page 63: uses of "contraL" should be "contraLR"

Page 64: "apply: prime_gt0" doesn't work, but "rewrite prime_gt0" does.

Page 106: "contraxposition"

**Comment by amahboubi** [comment]
Hello @sindikat! Thanks a lot for your feedback! We have actually already corrected the typos and mistakes you spotted. But the pdf version that is on the webpage was actually outdated :(... Thanks for having made us spotting that problem, and sorry about that! commit 3a49e72 corrects this, hence I am closing the issue.

**Comment by gares** [comment]
Yep, I think we should release a new PDF draft ASAP (even if not all PR have been taken into account)

**Comment by amahboubi** [comment]
@gares Actually my last commit 74f281a8261ea764e1989fcd12ad58b6077c4afc did refresh the pdf on the web page, but you merged some PRs since. I am all for frequent releases, not letting people read outdated version in vain. But may be  should we indicate a date/a sha on the web page next to the link. What do you think?

**Comment by gares** [comment]
Oh, I missed it.  The sha1 is in the PDF but the date next to it is hardcoded :-/ The website does not mention the sha1.  I'll look into these issues tomorrow
