### ISSUE TITLE
Suggestions on Chap. 2

### ISSUE THREAD

**Issue by remysucre** [math-comp/mcb#36]
Let me know if I should split this into multiple issues! 

Page number may be different; here I use the page numbers from the pdf compiled from source at the latest commit. 

p.57, S2.2: 
> Indeed it is a good practice to get rid of the easiest subgoals as early as possible

Why? Do they cost anything? 

> This proof script can actually be made more compact...

Why do people like to make Coq scripts compact? Very often when I try to understand a proof I have to expand it myself, so to interact with the tactics and see the intermediate results. 

> simplify switch

Why not just add // to every introduction by default? 

p.64
> apply: tactic

Chapter 3 points out ssr's apply: (with a colon) differs from Coq's apply (without). Might worth pointing out it here? 

> Hint Resolve

Why not tag every lemma with this? 

p. 65
> move

Chapter 3 makes clear why one needs to move the A in A -> B to the context, but from an implementation perspective. How does this correspond to pen and paper proofs? Why do I need to move the a in \forall a, e to perform a rewrite in e?

**Comment by gares** [comment]
Thanks for the comments!  A single issue is fine.  Unfortunately I don't think we will manage to address it before next fall...

A very short answer to the easy questions:
- easy subgoals have a short proof (1 line) and if you put them after the hard ones (having many lines of proof) then the distance between where a goal is generated and where it is tackled is bigger
- I understand the need of inspecting the state of Coq in the middle of a command, but I also think it should not drive our taste, but rather push us to improve our tools (i.e. you want a better debugger, not longer scripts)
- one, boring, reason is that // can be slow to fail...

**Comment by remysucre** [comment]
Thanks, that makes sense. I'm still not convinced of the benefits of short proofs. For regular programs, functional languages make code short and more readable with features like higher order functions. The Coq proofs are short indeed, but I don't find them readable. Or does it take experience to read Coq proofs without running it?

**Comment by gares** [comment]
> Why do I need to move the a in \forall a, e to perform a rewrite in e?

This is a typical question for beginners.  I'll answer here shortly, but I'm not sure where this could do.
BTW I've just pushed a commit that solves some of the issues you raised, thanks again!

Rewriting `f x` to `g x` (assuming you have a proof `e : forall x, f x=g x`) boils down to applying `eq_ind`
that has type (roughly) `forall P : A -> Prop, forall b, P b -> forall a, a = b -> P a`.  Hence the context under which
the replacement takes place has to be represented by `P`.  If your goal is
```
y : A
e : forall x, f x = g x
====
h (f y)
```
then `P` can be `fun a : A => h a`, and `eq_ind P (g y) ?new_goal (f y) (e y)` has type `P (f y)` that beta reduces to `h (f y)` (your current goal) while ?new_goal has type `P (g y)` that is `h (g y)` (that is going to be your new goal).
But If the goal is
```
e : forall x, f x = g x
====
forall y, h (f y)
```
the `P` can't be `fun a => forall y, h a` (since a does not se `y`).

Hope it helps,
